
DEBUG 2017-01-12 10:07:52,739 test NEW TEST LOOP
CRITICAL 2017-01-12 10:08:28,891 app OVERVOLTAGE ON SLAVE 4 REACHED, VOLTAGE NOW IS: 3.70
DEBUG 2017-01-12 10:08:29,107 app FOUND PYTHON PROCESS WITH ID: 4025
CRITICAL 2017-01-12 10:08:29,108 test EXITING TEST SCRIPT
DEBUG 2017-01-12 10:08:29,109 app Sent SIGTERM to process ID: 4025
DEBUG 2017-01-12 10:08:29,376 test Exception occured
DEBUG 2017-01-12 10:08:29,611 app FOUND PYTHON PROCESS WITH ID: 3555
DEBUG 2017-01-12 10:08:29,612 app FOUND PYTHON PROCESS WITH ID: 3533
DEBUG 2017-01-12 10:08:29,612 app FOUND PYTHON PROCESS WITH ID: 1608
CRITICAL 2017-01-12 10:08:29,891 app OVERVOLTAGE ON SLAVE 4 REACHED, VOLTAGE NOW IS: 3.70
DEBUG 2017-01-12 10:08:30,126 app FOUND PYTHON PROCESS WITH ID: 3555
DEBUG 2017-01-12 10:08:30,128 app FOUND PYTHON PROCESS WITH ID: 3533
DEBUG 2017-01-12 10:08:30,131 app FOUND PYTHON PROCESS WITH ID: 1608
CRITICAL 2017-01-12 10:08:30,895 app OVERVOLTAGE ON SLAVE 4 REACHED, VOLTAGE NOW IS: 3.70
DEBUG 2017-01-12 10:08:31,141 app FOUND PYTHON PROCESS WITH ID: 3555
DEBUG 2017-01-12 10:08:31,142 app FOUND PYTHON PROCESS WITH ID: 3533
DEBUG 2017-01-12 10:08:31,143 app FOUND PYTHON PROCESS WITH ID: 1608
